package lc.assignment61;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Luke Chen / Ankur Panchal
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    javax.swing.table.DefaultTableModel model;
    
    public UI() {
        initComponents();
        model = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelP = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jLabelM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel1.setSize(new java.awt.Dimension(130, 130));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Table");

        jLabelP.setBackground(new java.awt.Color(255, 255, 255));
        jLabelP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP.setText("papers");
        jLabelP.setOpaque(true);

        jLabelT.setBackground(new java.awt.Color(102, 51, 0));
        jLabelT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelT.setText("tobacco");
        jLabelT.setOpaque(true);

        jLabelM.setBackground(new java.awt.Color(0, 0, 0));
        jLabelM.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelM.setText("matches");
        jLabelM.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelP)
                .addGap(18, 18, 18)
                .addComponent(jLabelT)
                .addGap(18, 18, 18)
                .addComponent(jLabelM)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabelP.getAccessibleContext().setAccessibleName("papers");
        jLabelM.getAccessibleContext().setAccessibleName("matches");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null,  new Boolean(true),  new Boolean(true), null},
                {"2", null,  new Boolean(true),  new Boolean(true), null},
                {"3", null,  new Boolean(true),  new Boolean(true), null},
                {"4",  new Boolean(true), null,  new Boolean(true), null},
                {"5",  new Boolean(true), null,  new Boolean(true), null},
                {"6",  new Boolean(true), null,  new Boolean(true), null},
                {"7",  new Boolean(true),  new Boolean(true), null, null},
                {"8",  new Boolean(true),  new Boolean(true), null, null},
                {"9",  new Boolean(true),  new Boolean(true), null, null}
            },
            new String [] {
                "Smoker", "Paper", "Tobacco", "Match", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jTable1.setPreferredSize(new java.awt.Dimension(500, 150));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JLabel jLabelP;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void setjLabelMVisible(boolean visible) {
        this.jLabelM.setVisible(visible);
    }

    public void setjLabelPVisible(boolean visible) {
        this.jLabelP.setVisible(visible);
    }
    public void setjLabelTVisible(boolean visible) {
        this.jLabelT.setVisible(visible);
    }
    
}
